# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Evaluación gratuita (e472a9b1-7641-415b-8e14-5ba7aa1b225c)'
    AuthenticationType: 'server'
    ServerName: 'gestion-clientes.database.windows.net'
    DatabaseName: 'db-gestion-clientes'
    SqlUsername: 'amedc'
    SqlPassword: 'Kevin96*'
    deployType: 'DacpacTask'
    DeploymentAction: 'Script'
    IpDetectionMethod: 'AutoDetect'